package net.asheranderson.mccourse.item;

import net.minecraft.component.type.FoodComponent;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;

public class ModFoodComponents {
    public static final FoodComponent UNSTABLE_SOULROOT = new FoodComponent.Builder()
            .nutrition(10)
            .saturationModifier(10f)
            .statusEffect(new StatusEffectInstance(StatusEffects.DARKNESS, 200), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.WITHER, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.HUNGER, 20000), 1.0f)
            .build();
    public static final FoodComponent SOULROOT = new FoodComponent.Builder()
            .nutrition(10)
            .saturationModifier(10f)
            .build();
    public static final FoodComponent UNSTABLE_SOUL_BERRY = new FoodComponent.Builder()
            .nutrition(50)
            .saturationModifier(50f)
            .statusEffect(new StatusEffectInstance(StatusEffects.DARKNESS, 200), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.WITHER, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.HUNGER, 20000), 1.0f)
            .build();
    public static final FoodComponent SOUL_BERRY = new FoodComponent.Builder()
            .nutrition(50)
            .saturationModifier(50f)
            .build();
    public static final FoodComponent AMETHYST_SOUL_BERRY = new FoodComponent.Builder()
            .nutrition(75)
            .saturationModifier(75f)
            .statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .alwaysEdible()
            .build();
    public static final FoodComponent ENCHANTED_AMETHYST_SOUL_BERRY = new FoodComponent.Builder()
            .nutrition(100)
            .saturationModifier(100f)
            .statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.HASTE, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.JUMP_BOOST, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.INVISIBILITY, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.INSTANT_HEALTH, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SPEED, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.ABSORPTION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.NIGHT_VISION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.LUCK, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.HASTE, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.JUMP_BOOST, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.INSTANT_HEALTH, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SPEED, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.ABSORPTION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.LUCK, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .statusEffect(new StatusEffectInstance(StatusEffects.SATURATION, 20000), 1.0f)
            .alwaysEdible()
            .build();
}
