package net.asheranderson.mccourse.item;

import net.asheranderson.mccourse.MCCourseMod;
import net.asheranderson.mccourse.block.ModBlocks;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

import static net.asheranderson.mccourse.item.ModItems.*;
import static net.asheranderson.mccourse.item.ModItems.AMBER_HOE;

public class ModItemGroups {
    public static final ItemGroup MOD_ITEMS = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(MCCourseMod.MOD_ID, "mod_items"),
            FabricItemGroup.builder().icon(() -> new ItemStack(ModItems.SOUL_GEM))
                    .displayName(Text.translatable("itemgroup.mc-course.mod_items"))
                    .entries((displayContext, entries) -> {
                        entries.add(ModBlocks.BRIMSTONE);
                        entries.add(ModItems.RAW_NETHERITE);
                        entries.add(ModItems.NETHERITE);
                        entries.add(ModBlocks.NETHERITE_ORE);
                        entries.add(ModBlocks.NETHERITE_BLOCK);
                        entries.add(ModItems.FIRE_OPAL);
                        entries.add(ModBlocks.FIRE_OPAL_ORE);
                        entries.add(ModBlocks.FIRE_OPAL_BLOCK);
                        entries.add(ModBlocks.NIHILITY_STONE);
                        entries.add(ModItems.RAW_NULLSTEEL);
                        entries.add(ModItems.NULLSTEEL);
                        entries.add(ModBlocks.NULLSTEEL_ORE);
                        entries.add(ModBlocks.NULLSTEEL_BLOCK);
                        entries.add(ModItems.VOIDITE);
                        entries.add(ModBlocks.VOIDITE_ORE);
                        entries.add(ModBlocks.VOIDITE_BLOCK);
                        entries.add(ModBlocks.AMBER);
                        entries.add(ModItems.BISMUTH);
                        entries.add(ModBlocks.BISMUTH_BLOCK);
                        entries.add(ModItems.RAW_ADAMANT);
                        entries.add(ModItems.ADAMANT);
                        entries.add(ModBlocks.ADAMANT_ORE);
                        entries.add(ModBlocks.ADAMANT_BLOCK);
                        entries.add(ModItems.AETHERITE);
                        entries.add(ModBlocks.AETHERITE_ORE);
                        entries.add(ModBlocks.AETHERITE_BLOCK);
                        entries.add(ModBlocks.AETHERLAMP);
                        entries.add(ModBlocks.SHALE);
                        entries.add(ModItems.RAW_FLOODSTEEL);
                        entries.add(ModItems.FLOODSTEEL);
                        entries.add(ModBlocks.FLOODSTEEL_ORE);
                        entries.add(ModBlocks.FLOODSTEEL_BLOCK);
                        entries.add(ModItems.AQUAMARINE);
                        entries.add(ModBlocks.AQUAMARINE_ORE);
                        entries.add(ModBlocks.AQUAMARINE_BLOCK);
                        entries.add(ModBlocks.ANGELITE);
                        entries.add(ModItems.RAW_FROSTSTEEL);
                        entries.add(ModItems.FROSTSTEEL);
                        entries.add(ModBlocks.FROSTSTEEL_ORE);
                        entries.add(ModBlocks.FROSTSTEEL_BLOCK);
                        entries.add(ModItems.FROSTINE);
                        entries.add(ModBlocks.FROSTINE_ORE);
                        entries.add(ModBlocks.FROSTINE_BLOCK);
                        entries.add(ModBlocks.CINNABAR);
                        entries.add(ModItems.RAW_BERYLLIUM);
                        entries.add(ModItems.BERYLLIUM);
                        entries.add(ModBlocks.BERYLLIUM_ORE);
                        entries.add(ModBlocks.BERYLLIUM_BLOCK);
                        entries.add(ModItems.AUTUNITE);
                        entries.add(ModBlocks.AUTUNITE_ORE);
                        entries.add(ModBlocks.AUTUNITE_BLOCK);
                        entries.add(ModBlocks.SOUL_STABILIZER);
                        entries.add(ModBlocks.SCULKIFIER);
                        entries.add(ModBlocks.UNSTABLE_SOUL_STONE);
                        entries.add(ModBlocks.SOUL_STONE);
                        entries.add(ModItems.RAW_UNSTABLE_SOULSTEEL);
                        entries.add(ModItems.RAW_SOULSTEEL);
                        entries.add(ModItems.UNSTABLE_SOULSTEEL);
                        entries.add(ModItems.SOULSTEEL);
                        entries.add(ModBlocks.SOULSTEEL_ORE);
                        entries.add(ModBlocks.UNSTABLE_SOULSTEEL_BLOCK);
                        entries.add(ModBlocks.SOULSTEEL_BLOCK);
                        entries.add(ModItems.UNSTABLE_SOUL_GEM);
                        entries.add(ModItems.SOUL_GEM);
                        entries.add(ModBlocks.SOULITE_ORE);
                        entries.add(ModBlocks.UNSTABLE_SOUL_GEM_BLOCK);
                        entries.add(ModBlocks.SOUL_GEM_BLOCK);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_STAIRS);
                        entries.add(ModBlocks.SOULITE_STAIRS);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_SLAB);
                        entries.add(ModBlocks.SOULITE_SLAB);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_BUTTON);
                        entries.add(ModBlocks.SOULITE_BUTTON);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_PRESSURE_PLATE);
                        entries.add(ModBlocks.SOULITE_PRESSURE_PLATE);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_FENCE);
                        entries.add(ModBlocks.SOULITE_FENCE);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_FENCE_GATE);
                        entries.add(ModBlocks.SOULITE_FENCE_GATE);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_WALL);
                        entries.add(ModBlocks.SOULITE_WALL);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_DOOR);
                        entries.add(ModBlocks.SOULITE_DOOR);
                        entries.add(ModBlocks.UNSTABLE_SOULITE_TRAPDOOR);
                        entries.add(ModBlocks.SOULITE_TRAPDOOR);
                        entries.add(UNSTABLE_SOULROOT);
                        entries.add(SOULROOT);
                        entries.add(UNSTABLE_SOUL_BERRY);
                        entries.add(SOUL_BERRY);
                        entries.add(AMETHYST_SOUL_BERRY);
                        entries.add(ENCHANTED_AMETHYST_SOUL_BERRY);
                        entries.add(OBSIDIAN_SWORD);
                        entries.add(OBSIDIAN_AXE);
                        entries.add(OBSIDIAN_PICKAXE);
                        entries.add(OBSIDIAN_SHOVEL);
                        entries.add(OBSIDIAN_HOE);
                        entries.add(NIHILITY_STONE_SWORD);
                        entries.add(NIHILITY_STONE_AXE);
                        entries.add(NIHILITY_STONE_PICKAXE);
                        entries.add(NIHILITY_STONE_SHOVEL);
                        entries.add(NIHILITY_STONE_HOE);
                        entries.add(NULLSTEEL_SWORD);
                        entries.add(NULLSTEEL_AXE);
                        entries.add(NULLSTEEL_PICKAXE);
                        entries.add(NULLSTEEL_SHOVEL);
                        entries.add(NULLSTEEL_HOE);
                        entries.add(VOIDITE_SWORD);
                        entries.add(VOIDITE_AXE);
                        entries.add(VOIDITE_PICKAXE);
                        entries.add(VOIDITE_SHOVEL);
                        entries.add(VOIDITE_HOE);
                        entries.add(BRIMSTONE_SWORD);
                        entries.add(BRIMSTONE_AXE);
                        entries.add(BRIMSTONE_PICKAXE);
                        entries.add(BRIMSTONE_SHOVEL);
                        entries.add(BRIMSTONE_HOE);
                        entries.add(NETHERITE_SWORD);
                        entries.add(NETHERITE_AXE);
                        entries.add(NETHERITE_PICKAXE);
                        entries.add(NETHERITE_SHOVEL);
                        entries.add(NETHERITE_HOE);
                        entries.add(FIRE_OPAL_SWORD);
                        entries.add(FIRE_OPAL_AXE);
                        entries.add(FIRE_OPAL_PICKAXE);
                        entries.add(FIRE_OPAL_SHOVEL);
                        entries.add(FIRE_OPAL_HOE);
                        entries.add(AMBER_SWORD);
                        entries.add(AMBER_AXE);
                        entries.add(AMBER_PICKAXE);
                        entries.add(AMBER_SHOVEL);
                        entries.add(AMBER_HOE);
                        entries.add(ADAMANT_SWORD);
                        entries.add(ADAMANT_AXE);
                        entries.add(ADAMANT_PICKAXE);
                        entries.add(ADAMANT_SHOVEL);
                        entries.add(ADAMANT_HOE);
                        entries.add(AETHERITE_SWORD);
                        entries.add(AETHERITE_AXE);
                        entries.add(AETHERITE_PICKAXE);
                        entries.add(AETHERITE_SHOVEL);
                        entries.add(AETHERITE_HOE);
                        entries.add(ModItems.AMBER_WARHAMMER);
                        entries.add(SOULFIRE_CORE);
                    }).build());
    public static void registerItemGroups() {
        MCCourseMod.LOGGER.info("Registering Items for "+ MCCourseMod.MOD_ID);
    }
}
